language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: bmaWXf92ph0nO1S9I7D5Un0FJeSf3UPGGbssZi0WFN+AY4tQ15Tg3Cu5OKOtK8eK3aUy3Re2mcBpnWpH/TMvT/fZui5E876eRIU45JNsUbGePYLjILJzXtvkOO8GskKziCDaL2bTMjlrAYmfo0uKSEma6bOnwGuJW5Xm9F8WOwEkLxTIEOyxpfKv+VUQVKRMMsoNLSc5Rs3pXAr1W+eVxh7t9Pr3xh+JVZKwkHmtPgkheaIXAMAmAghtyPLYcxR7/RtEihmhu8h7SVX2m8u3VRgX05ZAMG865VfsLOzNl2WblvAjnQxLwdFdZUeIUlcaJ2wDpmo+jOJZeTF9cXNZfqnnG/RVU53B5SLB2ON955lh6qoA6ANQsUM2czItBe+V/aaH0J1pFZAwElXb6HREWHmNCcv57eU6eyeynENlF6d/yuBePCvLLXsysLL4Vsoa5uXdTtxT+EM1PK9+XYW8lHNoswsN1tnWIpmaHO6Sw2E55vPaezWls3JNN2+49ne7iusmzokodvcxVhP6qMZvQziJ35kgD1BCxCztLGIh5RAdp10ZGW874F+um++egQrqXsvHFoFaeTyFVobnOzpFyJFL31scubhUHOARIxt5LjXs0O5Hu4G+wX6RSrSxuSo3n+khdQGhmfdONgegCjSQSRTuJBsn8X+pol38UWGBf9E=
  app: boiling-mountain-47103
  on:
    repo: rusye/znayti-server
